### ISSUE TITLE
corrupt binary uploads - headers inserted at top of file on the target

### ISSUE THREAD

**Issue by rowntreerob** [SamDecrock/node-httpreq#13]
Using post to upload an mp4, once on the target, about 230 bytes of extra stuff appearing at head and tail of the file..

Extra bytes at Head...

-----------------------------uVaomvfVmZtjdNpVRQRGm1iSnxKwc
Content-Disposition: file; name="myfile"; filename="my-movie.mp4"
Content-Type: application/octet-stream

Extra bytes at Tail...

-----------------------------uVaomvfVmZtjdNpVRQRGm1iSnxKwc--

noticed similar issue [ here](https://github.com/request/request/issues/1160)

my code....

`var httpreq = require('httpreq');

  httpreq.post('https://api.parse.com/1/files/'+postfile, {
    headers:{
        'X-Parse-Application-Id': 'Mrc7',
        'X-Parse-REST-API-Key': 'Kw7',
        'Content-Type': 'video/mp4'
    },
    files:{
        myfile: __dirname + "/" +postfile
    },
    binary: true
  },
`

-rw-rw-r-- 1 rob rob 209156 Sep 25 19:11 my-movie-corrupted.mp4

-rw-rw-r-- 1 rob rob 208923 Sep 25 18:59 my-movie.mp4

**Comment by SamDecrock** [comment]
What kind of webserver are you posting to? So I can replicate the problem. The "extra stuff" you're talking about is how "multipart/form-data" is POSTed to a webserver and should be perfectly normal.

**Comment by SamDecrock** [comment]
Nevermind, found the problem. Try removing the "Content-Type" header you're sending. You're overriding the default "multipart/form-data; boundary=xxx" which is nessecary for the webserver to understand that a multipart/form-data is being posted ;-)

**Comment by rowntreerob** [comment]
parse.com

REST.POST

https://parse.com/docs/rest/guide#files-uploading-files

**Comment by rowntreerob** [comment]
thanks ... i need a replica of

curl  -X POST  -H "X-Parse-Application-Id: qovv" -H "X-Parse-REST-API-Key:
heoj"  -H "Content-Type: video/mp4"  --data-binary @"$path$otfilname"
https://api.parse.com/1/files/"$otfilname"

note that  --data-binary with @path is a diff animal than 'multipart' with
the extra cruft in the data.pipe.

**Comment by rowntreerob** [comment]
im gonna try the 'pipe' to the request solution shown in

var request = require('request')
  , fs = require('fs')
  , FILE_PATH =  './1slide.pptx'
  , contentLength = fs.statSync(FILE_PATH).size
;var req = request.post({ url: 'http://echo.httpkit.com/',
  headers: {
    'x-auth-token': 'myToken',
    'content-length': contentLength
    }
  })
fs.createReadStream(FILE_PATH).pipe(req).pipe(process.stdout);

**Comment by rowntreerob** [comment]
try it without the content-type

still corrupted file

**Comment by rowntreerob** [comment]
workaround for post of binary file to parse.com using parse's REST. API...

i just used read.sync to load a buffer then,

  var myproc = httpreq.post('https://api.parse.com/1/files/'+postfile, {
    headers:{
        'X-Parse-Application-Id': 'Mrc7',
        'X-Parse-REST-API-Key': 'Kw7',
        'Content-Type': 'video/mp4'
    },
    binary: true,
    body: mybuffer
  }, function (err, res){
    if (err){
        deferred.reject(new Error(err));
    }else{
        deferred.resolve(res.body);
    }
  });

thanks 4 ur help

**Comment by SamDecrock** [comment]
That's a correct solution as you only want to send your mp4's bytes as the body, not using the standard HTTP multipart/form-data.

You can leave out ```{binary: true}``` as this is only needed when you're expecting a binary as a response.
