### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by fvdm** [SamDecrock/node-httpreq#16]
Hi Sam,

I'd like to clean up the code to make sure the style is consistent everywhere. It's a bit of a mess now.

Do you have a certain style or even styleguide in mind you'd like the code to follow?

**Comment by SamDecrock** [comment]
Hi, If you're OK with it, I'll make you a collaborator on the repository. That way, you can make changes without having to make pull requests. 

I don't have any style guides. You can even change the tab/space size if you like ;-)

Thanks,
Sam

**Comment by fvdm** [comment]
Great, thanks!
