### ISSUE TITLE
Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by SamDecrock** [SamDecrock/node-httpreq#28]
Getting 

```
(node:3393) Warning: Possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit
Warning: Possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:259:19)
    at Socket.addListener (events.js:275:10)
    at Socket.Readable.on (_stream_readable.js:687:35)
    at ClientRequest.<anonymous> (/Users/samdecrock/projects/awesomproject/app/node_modules/httpreq/lib/httpreq.js:420:14)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at tickOnSocket (_http_client.js:568:7)
    at onSocketNT (_http_client.js:580:5)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Seems like the timeout handlers keep adding up. I'm using a keep-alive agent, so that might cause the problem. 

@fvdm I saw that you switched to socket.on('timeout'), any reason why: https://github.com/SamDecrock/node-httpreq/commit/1428f5f9f44c5172fa56845429c8a52e3153cdbb ?

I'm going to switch back to using the `request.setTimeout()` handler.

**Comment by fvdm** [comment]
It's been a while, but iirc at the time the socket was handling all timeouts and the parent (request) did not always process correctly. By listening directly on the socket you'd basicly bypass the whole problem.

In which node version are you getting this error?

The commit is from 2 years ago, that was probably node v0.12, so maybe they finally fixed the request problem in recent versions.

**Comment by SamDecrock** [comment]
I'm currently using node v6.10.1

Problem is that the socket stays 'alive' and timeout handlers keep adding up. So to fix that, we would have to keep a reference of the socket object, keep a reference to the timeout handler and then remove the timeout handler from the socket the moment the request ends.

We'll see if this comes up as an issue using `request.setTimeout()`

**Comment by fvdm** [comment]
Okay.
