### ISSUE TITLE
Added 'head' support

### ISSUE THREAD

**Issue by happyrobotgames** [SamDecrock/node-httpreq#29]
Hi there. Not really an issue but I couldn't see a nice way to contact you - I added in support for http HEAD request as I needed it, and it was handy to have it for consistency. Modified httpreq is here. Would be great if you could drop it into master so we don't end up maintaining multiple versions (assuming you're happy with the code obviously!).

Also, thanks for a great a package!

[httpreq.js.txt](https://github.com/SamDecrock/node-httpreq/files/1208131/httpreq.js.txt)

**Comment by SamDecrock** [comment]
Thanks. Finally took the time to integrate it.
